In [1]:
import numpy as np
from numpy import genfromtxt

In [3]:
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
data.shape

(1372, 5)

In [6]:
labels = data[:, -1]

In [7]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [8]:
features = data[:, :4]

In [9]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [10]:
X = features
y = labels

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
X_train.max(axis=0)

array([ 6.8248, 12.9516, 17.9274,  2.1625])

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [21]:
scaler_object = MinMaxScaler()

In [22]:
scaler_object.fit(X_train)

MinMaxScaler()

In [24]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

scaled_X_train.max(axis=0)

array([1., 1., 1., 1.])

In [27]:
from keras.models import Sequential
from keras.layers import Dense

In [43]:
model = Sequential()

model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [49]:
model.fit(scaled_X_train, y_train,epochs=50, verbose=2)

Epoch 1/50
29/29 - 0s - loss: 0.1043 - accuracy: 0.9771
Epoch 2/50
29/29 - 0s - loss: 0.1014 - accuracy: 0.9761
Epoch 3/50
29/29 - 0s - loss: 0.0982 - accuracy: 0.9815
Epoch 4/50
29/29 - 0s - loss: 0.0954 - accuracy: 0.9815
Epoch 5/50
29/29 - 0s - loss: 0.0939 - accuracy: 0.9771
Epoch 6/50
29/29 - 0s - loss: 0.0906 - accuracy: 0.9804
Epoch 7/50
29/29 - 0s - loss: 0.0881 - accuracy: 0.9859
Epoch 8/50
29/29 - 0s - loss: 0.0865 - accuracy: 0.9848
Epoch 9/50
29/29 - 0s - loss: 0.0832 - accuracy: 0.9859
Epoch 10/50
29/29 - 0s - loss: 0.0808 - accuracy: 0.9902
Epoch 11/50
29/29 - 0s - loss: 0.0784 - accuracy: 0.9902
Epoch 12/50
29/29 - 0s - loss: 0.0767 - accuracy: 0.9891
Epoch 13/50
29/29 - 0s - loss: 0.0746 - accuracy: 0.9902
Epoch 14/50
29/29 - 0s - loss: 0.0730 - accuracy: 0.9902
Epoch 15/50
29/29 - 0s - loss: 0.0709 - accuracy: 0.9913
Epoch 16/50
29/29 - 0s - loss: 0.0694 - accuracy: 0.9935
Epoch 17/50
29/29 - 0s - loss: 0.0681 - accuracy: 0.9902
Epoch 18/50
29/29 - 0s - loss: 0.0663 - 

In [34]:
from sklearn.metrics import confusion_matrix, classification_report

In [37]:
 model.metrics_names

['loss', 'accuracy']

In [50]:
predictions = model.predict_classes(scaled_X_test)

In [51]:
confusion_matrix(y_test, predictions)

array([[256,   1],
       [  0, 196]], dtype=int64)

In [57]:
print(classification_report(y_test, predictions, digits=5))

              precision    recall  f1-score   support

         0.0    1.00000   0.99611   0.99805       257
         1.0    0.99492   1.00000   0.99746       196

    accuracy                        0.99779       453
   macro avg    0.99746   0.99805   0.99775       453
weighted avg    0.99780   0.99779   0.99779       453



In [56]:
y_test[y_test == 1.0].shape

(196,)

In [58]:
model.save('my_ANN_model.h5')